id: I6E2E04EE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T19:40:03+00:00'
last_modified: '2022-06-09T05:35:45.941591+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9275
  title: གཡུ་ཐོག་གསར་རྙིང་གི་རྣམ་ཐར་དང་བོད་སྨན་སྐོར་གྱི་ཟིན་ཐོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    F47C:
      image_group_id: I1KG9514
      title: Volume 1 of tibetan medicine notes
      total_pages: 272
      order: 1
      base_file: F47C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
