id: P007114
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9275
  title: གཡུ་ཐོག་གསར་རྙིང་གི་རྣམ་ཐར་དང་བོད་སྨན་སྐོར་གྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    989e4e5f0f96460e87cf508d919e6c3f:
      image_group_id: I1KG9514
      title: ''
      volume_number: 1
      total_pages: 272
ebook_metadata:
  title: གཡུ་ཐོག་གསར་རྙིང་གི་རྣམ་ཐར་དང་བོད་སྨན་སྐོར་གྱི་ཟིན་ཐོ།
  author: ''
  sku: P007114
  cover: cover.jpg
  layers:
  - pagination
