id: P007114
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG9275
  title: གཡུ་ཐོག་གསར་རྙིང་གི་རྣམ་ཐར་དང་བོད་སྨན་སྐོར་གྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    43b356f2b3c54103b3403d299a61dad5:
      image_group_id: I1KG9514
      title: Volume 1 of tibetan medicine notes
      volume_number: 1
      total_pages: 272
      base_file: v001.txt
